### ISSUE TITLE
Change color of the dome

### ISSUE THREAD

**Issue by TontonTremblay** [owl-project/ViSII#49]
Can we  change the color of the dome, e.g., set_color_dome.

**Comment by n8vm** [comment]
We're kinda in a bad spot when it comes to dome lights, since right now the default dome light isn't just one color, but rather an interpolated gradient between several colors depending on elevation. So set_dome_light_color results in an ill-defined procedural dome light with the current setup. 

I've also found that set_dome_light_color hasn't been very useful in the past. Generally, you only set the dome light to black or white through that function, since other colors like red, green, blue etc give very unrealistic and unpleasant images. (Remember, dome lights effect not only the background color, but also how all objects in the scene are lit up)

Really, you need some way to control the gradient of the dome light, add a sun, set time of day, etc. Something like this: [https://docs.unrealengine.com/en-US/Engine/Actors/FogEffects/SkyAtmosphere/index.html#:~:text=The%20Sky%20Atmosphere%20component%20in,atmospheres%20of%20an%20exotic%20nature.](https://docs.unrealengine.com/en-US/Engine/Actors/FogEffects/SkyAtmosphere/index.html#:~:text=The%20Sky%20Atmosphere%20component%20in,atmospheres%20of%20an%20exotic%20nature.)
And that can quickly become very complicated if it's incrementally implemented since different procedural dome lights conflict with each other.

I'd prefer we nail down some long term, robust API solution here.

**Comment by TontonTremblay** [comment]
So I guess the most useful solution is to use a dome hdr of one color?

**Comment by TontonTremblay** [comment]
Maybe we could add some predefined color domes for people to play around with.

**Comment by n8vm** [comment]
The current game plan here is to implement a version of this shader: https://www.shadertoy.com/view/tltGDM
We would bake out an HDRI from that shader, and then use that HDRI for importance sampling.

**Comment by n8vm** [comment]
This is now available in the latest version of visii using the visii.set_dome_light_color and visii.set_done_light_sky functions.
