### ISSUE TITLE
Intermittent crashing when adding/removing custom geometry every frame

### ISSUE THREAD

**Issue by lpisha** [owl-project/ViSII#68]
Steps to reproduce:

1. Check out the update_removal_test_2 branch.
2. Run examples/17.removal.py.
3. Observe CUDA kernel assertion failure with "buffer was nullptr" error message after about 10-20 frames.

**Comment by n8vm** [comment]
After working with @lpisha, I don’t believe this is a problem anymore. There were some race conditions previously that were causing this crash to happen, but those have since been fixed with the newer recursive mutex pattern used by components. 

If crashing still occurs, please leave a comment on this issue or open another and I can check it out. :)
