### ISSUE TITLE
00.helloworld.py error

### ISSUE THREAD

**Issue by kennyworkman** [owl-project/ViSII#69]
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error: Failed to initialize 0
Aborted (core dumped)
```

Other example files (`01.simple_scene.py`) run fine

**Comment by n8vm** [comment]
Hey Kenny,

Could you let me know how your system is setup? OS, GPU configuration, etc.

I’m wondering if the “ViSII.initialize_interactive()” is failing to create an OpenGL window for some reason. If you edit sample 1 to call “initialize_interactive” instead of “initialize_headless”, does sample 1 give the same error?

**Comment by n8vm** [comment]
Hi @kennyworkman,

Are you still running into this issue?

**Comment by n8vm** [comment]
Closing, since I haven't heard back. Please open again if this is still an issue for you.

**Comment by Kartoffelchen** [comment]
> Closing, since I haven't heard back. Please open again if this is still an issue for you.

Hey Natevm, I confronted the same problem.
My Nvidia driver is 460.73.1, system is Ubuntu 18.04.

To run the 00.helloworld.py, and the error was like this:
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error: Failed to create OpenGL window. Minimum OpenGL version is 4.3.
Aborted (core dumped)
